### PR TITLE
Add language to the Fetch query endpoint #15

### PR DESCRIPTION
**Pull request by khushijindal**

### CODE REVIEW

**Comment by DGaffney** [comment]
@huslage this test looks like some error on AWS credentials - any ideas?

**Comment by DGaffney** [comment]
@khushijindal exciting! Thanks for this PR. End of the work day where I am but we will incorporate this!

**Comment by khushijindal** [comment]
@DGaffney I am confused on these tests part though.

**Comment by DGaffney** [comment]
@khushijindal the error seems to be on our end with our continuous integration. Not sure but I believe that's what's hold things back right now. I'm offline starting now through the weekend but I will look deeper on monday!

**Comment by DGaffney** [comment]
Hello! @khushijindal I went ahead and tested your code locally and it doesn't break any local tests on my machine. I also looked into the unit tests and I'd advise building a test like the `'expects claim_review_search_query hash, empty single time'` task in `spec/lib/elastic_search_query_test.rb`. @huslage do let me know if we can chat about the error @khushijindal is hitting - still seems like something on our end from my perspective.

**Comment by khushijindal** [comment]
Hey, @DGaffney I looked into the tests part when I was working on the issue, but couldn't actually understand it, can you help a bit by explaining what needs to be done.

**Comment by DGaffney** [comment]
@khushijindal sure thing - I think your test would look something like the following:

```
    it 'expects claim_review_search_query hash with a language specified' do
      expect(described_class.claim_review_search_query({service: 'google', language: "en"})).to(eq({ size: 20, from: 0, sort: [{created_at:{order: 'desc'}}], query: { bool: { must: [{ match_all: {} }], filter: [{ match_phrase: { 'service' => 'google' } }, { match_phrase: { "language" => "en" } }] , should: [], must_not: [] } } }))
    end
```

Effectively, as an MVP unit test, we need to confirm that we can create a valid elasticsearch query with the language parameter being passed through.

Additionally, we'll need an integration test that ensures that the query can actually work that would look something like the following inside `spec/lib/db_integration_test.rb`:

```
    it "ensures access of #{subclass} via Search-layer" do
      expect(ClaimReview.search(language: "en")[0][:url]).to(eq(@storage_results[subclass][0][:claim_review_url]))
    end
```

Finally, one thing I didn't see yet, and needs to be in there _regardless of this feature getting finished_ is we need to expose the `language` that is currently being stored in ElasticSearch in the `ClaimReview` Schema by adding a line to the `lib/claim_review_export.rb` file:

```
      "inLanguage": claim_review['language'],
```

This needs to be under the `inLanguage` key in order to be `ClaimReview`-compliant.

Does this help clarify anything? We've also looked at the failure you're hitting and over here at Meedan we're in agreement that it's an error on our end.

**Comment by khushijindal** [comment]
Yes, surely @DGaffney , it helps. I'll work on this too and get back.

**Comment by khushijindal** [comment]
@DGaffney , I tried to do as you instructed. Please review and if there is some problem, please tell me.

**Comment by DGaffney** [comment]
@huslage how should we handle the breaking tests here?

**Comment by DGaffney** [comment]
@khushijindal Unfortunately, due to the error you're running into, we have to open a new PR to test this. I opened up https://github.com/meedan/fetch/pull/65 which incorporates your changes and allows testing of it. If it's alright, I'd like to move over to that ticket instead, and we can finish incorporating the code there (albeit with my name attached to the changes, unfortunately)? Let me know if that's acceptable to you.

**Comment by DGaffney** [comment]
Closing PR - your changes have been incorporated on the other branch, @khushijindal!

**Comment by khushijindal** [comment]
Hey @DGaffney, I think so you have merged the changes on another PR. As I am participating in Hacktoberfest, as these changes are not merged, my PR would be labelled invalid. So, please at least add hacktoberfest-accepted label. I have started with open-source recently, so these PRs are very important to me. I wanted to raise a new PR incorporating all changes, so it could be merged, but now it has been done, so ok!

**Comment by huslage** [comment]
@khushijindal I have added the label for you. Thanks so much for the contribution!

**Comment by khushijindal** [comment]
@huslage can you please explain to me like where exactly were errors occurring, would be helpful for me in the future. I think so PR from the forked repo fails the AWS credentials .

**Comment by huslage** [comment]
You're right. The forked repo can't read the AWS credentials. We are
working to fix the problem.

**Comment by DGaffney** [comment]
@khushijindal sorry that the fork you opened wasn't the one that directly resulted in the code being accepted - it is a problem on our end and I apologize for that. Thank you *so* much for your contribution, it's very appreciated.

**Pull request closed without merging**
